# Generated by Django 5.1 on 2024-09-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bus_type', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('reviews_count', models.IntegerField()),
                ('departure_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('duration', models.CharField(max_length=100)),
                ('arrival_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('seats_left', models.IntegerField()),
                ('window_seats', models.IntegerField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('policies', models.JSONField()),
                ('photos', models.JSONField()),
                ('amenities', models.JSONField()),
                ('pickups_drops', models.JSONField()),
            ],
        ),
    ]
