# Generated by Django 5.1 on 2024-09-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='bus_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='reviews_count',
        ),
        migrations.AddField(
            model_name='bus',
            name='reviews',
            field=models.JSONField(default=list),
        ),
    ]
