# Generated by Django 5.1 on 2024-09-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_rename_bus_type_bus_type_remove_bus_reviews_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='type',
            new_name='bus_type',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='reviews',
            new_name='review_texts',
        ),
        migrations.AddField(
            model_name='bus',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='bus',
            name='photos',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='bus',
            name='pickups_drops',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='bus',
            name='policies',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='bus',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
