# Generated by Django 5.1 on 2024-09-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_rename_type_bus_bus_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
