# Generated by Django 5.1 on 2024-09-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_alter_bus_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='review_texts',
            new_name='reviews_texts',
        ),
    ]
