# Generated by Django 5.1 on 2024-08-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='destination_code',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='origin_code',
            new_name='origin',
        ),
    ]
