# Generated by Django 5.1 on 2024-08-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_rename_destination_code_flight_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('duration', models.CharField(max_length=50)),
                ('arrival_time', models.TimeField()),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stops', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=200)),
            ],
        ),
    ]
