# Generated by Django 5.1 on 2024-09-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('departure_time', models.TimeField()),
                ('departure_day', models.CharField(max_length=10)),
                ('departure_station', models.CharField(max_length=255)),
                ('departure_code', models.CharField(max_length=10)),
                ('arrival_time', models.TimeField()),
                ('arrival_day', models.CharField(max_length=10)),
                ('arrival_station', models.CharField(max_length=255)),
                ('arrival_code', models.CharField(max_length=10)),
                ('travel_time', models.CharField(max_length=20)),
                ('ac_seat_number', models.CharField(max_length=20)),
                ('ac_coach_number', models.CharField(max_length=10)),
                ('ac_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('non_ac_seat_number', models.CharField(max_length=20)),
                ('non_ac_coach_number', models.CharField(max_length=10)),
                ('non_ac_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sleeper_seat_number', models.CharField(max_length=20)),
                ('sleeper_coach_number', models.CharField(max_length=10)),
                ('sleeper_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(max_length=20)),
                ('route', models.JSONField()),
            ],
        ),
    ]
