# Generated by Django 5.1 on 2024-09-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='ac_coach_number',
            new_name='acCoachNumber',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='ac_price',
            new_name='acPrice',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='ac_seat_number',
            new_name='acSeatNumber',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='arrival_code',
            new_name='arrivalCode',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='arrival_day',
            new_name='arrivalDay',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='arrival_station',
            new_name='arrivalStation',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='arrival_time',
            new_name='arrivalTime',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='departure_code',
            new_name='departureCode',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='departure_day',
            new_name='departureDay',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='departure_station',
            new_name='departureStation',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='departure_time',
            new_name='departureTime',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='non_ac_coach_number',
            new_name='nonAcCoachNumber',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='non_ac_price',
            new_name='nonAcPrice',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='non_ac_seat_number',
            new_name='nonAcSeatNumber',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='sleeper_coach_number',
            new_name='sleeperCoachNumber',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='sleeper_price',
            new_name='sleeperPrice',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='sleeper_seat_number',
            new_name='sleeperSeatNumber',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='travel_time',
            new_name='travelTime',
        ),
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
