# Generated by Django 5.1 on 2024-09-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='fromCity',
            field=models.CharField(default='Goa', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='toCity',
            field=models.CharField(default='Mumbai', max_length=122),
            preserve_default=False,
        ),
    ]
