# Generated by Django 5.1 on 2024-09-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cab_type', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=20)),
                ('seats', models.IntegerField()),
                ('ac', models.BooleanField(default=True)),
                ('included_kms', models.IntegerField()),
                ('extra_km_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
