# Generated by Django 5.1 on 2024-09-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cab',
            old_name='name',
            new_name='cab_name',
        ),
        migrations.RenameField(
            model_name='cab',
            old_name='included_kms',
            new_name='distance_included',
        ),
        migrations.RenameField(
            model_name='cab',
            old_name='ac',
            new_name='is_ac',
        ),
        migrations.RenameField(
            model_name='cab',
            old_name='seats',
            new_name='seating_capacity',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='image_url',
        ),
    ]
