# Generated by Django 5.1 on 2024-09-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0002_rename_name_cab_cab_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='fromLocation',
            field=models.CharField(default='Goa', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cab',
            name='toLocation',
            field=models.CharField(default='Mumbai', max_length=122),
            preserve_default=False,
        ),
    ]
