# Generated by Django 5.1 on 2024-08-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('distance_to_beach', models.DecimalField(decimal_places=2, max_digits=5)),
                ('property_type', models.CharField(max_length=50)),
                ('sleeps', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('num_ratings', models.IntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes_and_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('amenities', models.CharField(max_length=255)),
                ('booking_url', models.URLField()),
                ('emi_offer', models.CharField(max_length=255)),
            ],
        ),
    ]
