buses = [
  {
    'id':1,
    "name": "Zingbus Plus",
    "bus_type": "Bharat Benz A/C Seater / Sleeper (2+1)",
    "rating": 4.8,
    "review_count": 238,
    "departure_time": "23:25",  
    "departure_date": "2021-09-12",
    "duration": "08hrs 40mins",
    "arrival_time": "08:05",
    "arrival_date": "2021-09-13",
    "seats_left": 37,
    "window_seats": 12,
    "original_price": 456,
    "discounted_price": 399,
    "discount": 57,
    "policies": ["Free Cancellation", "Instant Refund"],
    "photos": [
      "https://images.unsplash.com/photo-1723526680296-2c76e4729fa1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGJ1c2VzfGVufDB8fDB8fHww",
      "https://media.istockphoto.com/id/2160254015/photo/young-woman-using-mobile-phone-on-bus.webp?a=1&b=1&s=612x612&w=0&k=20&c=Ck3j15uotAEuNVmkqc67H9Mhy7tCeuskAlVovNkeGZc="
    ],
    "amenities": ["Wi-Fi", "Charging Port", "Blankets", "Water Bottle"],
    "pickups_drops": ["Delhi", "Noida", "Gurgaon"],
    "reviews_texts": ["Comfortable journey", "Clean seats"]
  },
  {
    'id':2,
    "name": "Orange Travels",
    "bus_type": "Volvo Multi-Axle Sleeper (2+1)",
    "rating": 4.5,
    "review_count": 320,
    "departure_time": "22:30",
    "departure_date": "2021-09-15",
    "duration": "10hrs 15mins",
    "arrival_time": "08:45",
    "arrival_date": "2021-09-15",
    "seats_left": 20,
    "window_seats": 8,
    "original_price": 600,
    "discounted_price": 525,
    "discount": 75,
    "policies": ["Free Cancellation"],
    "photos": [
      "https://images.unsplash.com/photo-1564694202883-46e7448c1b26?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YnVzZXN8ZW58MHx8MHx8fDA%3D",
      "https://images.unsplash.com/photo-1581025026681-4ed822ae7a15?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YnVzZXN8ZW58MHx8MHx8fDA%3D"
    ],
    "amenities": ["Wi-Fi", "Charging Port", "Blankets"],
    "pickups_drops": ["Hyderabad", "Bangalore", "Chennai"],
    "reviews_texts": ["Great service", "Clean bus"]
  },
  {
    'id':3,
    "name": "SRS Travels",
    "bus_type": "Scania Multi-Axle Semi-Sleeper (2+2)",
    "rating": 4.3,
    "review_count": 295,
    "departure_time": "21:15",
    "departure_date": "2021-09-14",
    "duration": "09hrs 20mins",
    "arrival_time": "06:35",
    "arrival_date": "2021-09-15",
    "seats_left": 25,
    "window_seats": 10,
    "original_price": 550,
    "discounted_price": 480,
    "discount": 70,
    "policies": ["Instant Refund"],
    "photos": [
      "https://plus.unsplash.com/premium_photo-1664302152991-d013ff125f3f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8YnVzZXN8ZW58MHx8MHx8fDA%3D",
      "https://images.unsplash.com/photo-1526129318478-62ed807ebdf9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YnVzZXN8ZW58MHx8MHx8fDA%3D"
    ],
    "amenities": ["Charging Port", "Water Bottle", "Air Conditioning"],
    "pickups_drops": ["Mumbai", "Pune", "Surat"],
    "reviews_texts": ["Smooth ride", "Good staff behavior"]
  },
  {
    'id':4,
    "name": "VRL Travels",
    "bus_type": "Volvo Multi-Axle I-Shift A/C Semi-Sleeper (2+2)",
    "rating": 4.6,
    "review_count": 210,
    "departure_time": "23:55",
    "departure_date": "2021-09-13",
    "duration": "11hrs 00mins",
    "arrival_time": "10:55",
    "arrival_date": "2021-09-14",
    "seats_left": 15,
    "window_seats": 5,
    "original_price": 720,
    "discounted_price": 650,
    "discount": 70,
    "policies": ["Free Cancellation", "Instant Refund"],
    "photos": [
      "https://plus.unsplash.com/premium_photo-1661963542752-9a8a1d72fb28?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YnVzZXN8ZW58MHx8MHx8fDA%3D",
      "https://images.unsplash.com/photo-1520023425914-16378de44260?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YnVzZXN8ZW58MHx8MHx8fDA%3D"
    ],
    "amenities": ["Wi-Fi", "Charging Port", "Blankets", "Pillow"],
    "pickups_drops": ["Ahmedabad", "Rajkot", "Vadodara"],
    "reviews_texts": ["Comfortable seats", "Well-maintained bus"]
  },
  {
    'id':5,
    "name": "KSRTC",
    "bus_type": "Non-A/C Sleeper (2+1)",
    "rating": 4.0,
    "review_count": 180,
    "departure_time": "20:10",
    "departure_date": "2021-09-13",
    "duration": "07hrs 55mins",
    "arrival_time": "04:05",
    "arrival_date": "2021-09-14",
    "seats_left": 10,
    "window_seats": 4,
    "original_price": 350,
    "discounted_price": 300,
    "discount": 50,
    "policies": ["Free Cancellation"],
    "photos": [
      "https://media.istockphoto.com/id/872753900/photo/bus-terminal.webp?a=1&b=1&s=612x612&w=0&k=20&c=j2KzvJ0iJC06bjve37VHvD4VCFaIhavQ5-UuLJ90b1E=",
      "https://media.istockphoto.com/id/1061230546/photo/young-handsome-man-relaxing-in-seat-of-tour-bus.webp?a=1&b=1&s=612x612&w=0&k=20&c=5hytQS5jC0z6gARzFHf9mpUHvsJW3UeofN2Ea1qVyE4="
    ],
    "amenities": ["Water Bottle", "Blankets"],
    "pickups_drops": ["Mysore", "Coimbatore", "Bangalore"],
    "reviews_texts": ["Affordable travel", "Basic service"]
  },
  {
    'id':6,
    "name": "Parveen Travels",
    "bus_type": "Mercedes Benz A/C Sleeper (2+1)",
    "rating": 4.9,
    "review_count": 175,
    "departure_time": "18:00",
    "departure_date": "2021-09-12",
    "duration": "12hrs 10mins",
    "arrival_time": "06:10",
    "arrival_date": "2021-09-13",
    "seats_left": 9,
    "window_seats": 3,
    "original_price": 800,
    "discounted_price": 700,
    "discount": 100,
    "policies": ["Free Cancellation", "Instant Refund"],
    "photos": [
      "https://media.istockphoto.com/id/1154164634/photo/white-bus-traveling-on-the-asphalt-road-around-line-of-trees-in-rural-landscape-at-sunset.webp?a=1&b=1&s=612x612&w=0&k=20&c=_dH385DEwAvUEDBVsCKlze-1Gws9R461itlgRJ2xTm8=",
      "https://media.istockphoto.com/id/1456618733/photo/electric-bus-with-charging-station.webp?a=1&b=1&s=612x612&w=0&k=20&c=T2s-BQYrbZf--Y0q9VRs2wlGXpvXcO0mGlnQ11EgumE="
    ],
    "amenities": ["Wi-Fi", "Charging Port", "Blankets", "Reading Lights"],
    "pickups_drops": ["Chennai", "Madurai", "Trichy"],
    "reviews_texts": ["Excellent service", "Luxurious experience"]
  },
  {
    'id':7,
    "name": "Kallada Travels",
    "bus_type": "Volvo Multi-Axle A/C Sleeper (2+1)",
    "rating": 4.7,
    "review_count": 312,
    "departure_time": "22:45",
    "departure_date": "2021-09-12",
    "duration": "09hrs 45mins",
    "arrival_time": "08:30",
    "arrival_date": "2021-09-12",
    "seats_left": 12,
    "window_seats": 5,
    "original_price": 680,
    "discounted_price": 620,
    "discount": 60,
    "policies": ["Free Cancellation", "Instant Refund"],
    "photos": [
      "https://media.istockphoto.com/id/1137162567/photo/tourist-buses-on-parking.webp?a=1&b=1&s=612x612&w=0&k=20&c=vrWwU-MZzHWT2KdFdIgbQTyydyw_A2qo8UmA9kFSfJk=",
      "https://media.istockphoto.com/id/1470569235/photo/electric-city-bus-recharging-at-the-bus-charge-station-connected-with-a-power-cable.webp?a=1&b=1&s=612x612&w=0&k=20&c=3q00NuYiDM6A-w5stnguvXa2jjsBQGJ5-xDuG49riMA="
    ],
    "amenities": ["Wi-Fi", "Charging Port", "Water Bottle"],
    "pickups_drops": ["Kochi", "Thrissur", "Bangalore"],
    "reviews_texts": ["Professional service", "Timely departure"]
  },
  {
    'id':8,
    "name": "Sundaram Travels",
    "bus_type": "Ashok Leyland A/C Seater (2+2)",
    "rating": 4.2,
    "review_count": 245,
    "departure_time": "19:30",
    "departure_date": "2021-09-11",
    "duration": "10hrs 25mins",
    "arrival_time": "05:55",
    "arrival_date": "2021-09-12",
    "seats_left": 30,
    "window_seats": 10,
    "original_price": 500,
    "discounted_price": 450,
    "discount": 50,
    "policies": ["Free Cancellation"],
    "photos": [
      "https://media.istockphoto.com/id/1140611116/photo/excited-to-travel.webp?a=1&b=1&s=612x612&w=0&k=20&c=xbxxUPsJHd4SmrMWZYzxi6z6LoRcCWf_opKJ5PfDJCQ=",
      "https://media.istockphoto.com/id/1508210601/photo/electric-bus-supercharging-station.webp?a=1&b=1&s=612x612&w=0&k=20&c=xffnIhxkmAmfmzsEA7Uow4KctsbW_flMAbprOOSo2j4="
    ],
    "amenities": ["Charging Port", "Water Bottle", "Wi-Fi"],
    "pickups_drops": ["Trivandrum", "Bangalore", "Coimbatore"],
    "reviews_texts": ["Well-maintained bus", "Polite staff"]
  },
  {
    'id':9,
    "name": "KPN Travels",
    "bus_type": "Volvo Multi-Axle Sleeper (2+1)",
    "rating": 4.4,
    "review_count": 198,
    "departure_time": "20:15",
    "departure_date": "2021-09-13",
    "duration": "11hrs 40mins",
    "arrival_time": "07:55",
    "arrival_date": "2021-09-14",
    "seats_left": 18,
    "window_seats": 7,
    "original_price": 620,
    "discounted_price": 550,
    "discount": 70,
    "policies": ["Free Cancellation", "Instant Refund"],
    "photos": [
      "https://media.istockphoto.com/id/1095141322/photo/bus-traveling-on-the-asphalt-road-in-rural-landscape-at-sunset.webp?a=1&b=1&s=612x612&w=0&k=20&c=sWZOFDZ4gSW5KEDazWFfrSfy2cZzjnm9wjFnp7V5hKs=",
      "https://media.istockphoto.com/id/825636218/photo/morning-rush-bus-stand-in-bangalore.webp?a=1&b=1&s=612x612&w=0&k=20&c=TSVeiBd_EYRvNybRRbiruolV-Crwy9XRSLp1s1ijoYI="
    ],
    "amenities": ["Wi-Fi", "Charging Port", "Blankets", "Water Bottle"],
    "pickups_drops": ["Salem", "Tirunelveli", "Bangalore"],
    "reviews_texts": ["Value for money", "Good staff"]
  },
  {
    'id':10,
    "name": "National Travels",
    "bus_type": "Ashok Leyland A/C Sleeper (2+1)",
    "rating": 4.0,
    "review_count": 190,
    "departure_time": "21:45",
    "departure_date": "2021-09-11",
    "duration": "08hrs 55mins",
    "arrival_time": "06:40",
    "arrival_date": "2021-09-12",
    "seats_left": 22,
    "window_seats": 6,
    "original_price": 480,
    "discounted_price": 420,
    "discount": 60,
    "policies": ["Free Cancellation"],
    "photos": [
      "https://media.istockphoto.com/id/1652672359/photo/in-the-bus-running-in-the-city-of-kollam-india.webp?a=1&b=1&s=612x612&w=0&k=20&c=KGvttmlWxkt2Q8rkn827WnNtn3ETlfGLJMHOD4yDc5g=",
      "https://media.istockphoto.com/id/881545572/photo/traffic-on-highway.webp?a=1&b=1&s=612x612&w=0&k=20&c=-9NUavGrQRAwVizrTuAGpE1Nz5LvN8QGF7HwEHd9ZpE="
    ],
    "amenities": ["Wi-Fi", "Charging Port", "Blankets"],
    "pickups_drops": ["Hubli", "Belgaum", "Bangalore"],
    "reviews_texts": ["Comfortable journey", "Good service"]
  },
  {
    'id':11,
    "name": "Sharma Transports",
    "bus_type": "Volvo A/C Seater Semi-Sleeper (2+2)",
    "rating": 4.5,
    "review_count": 220,
    "departure_time": "19:45",
    "departure_date": "2021-09-14",
    "duration": "09hrs 50mins",
    "arrival_time": "05:35",
    "arrival_date": "2021-09-15",
    "seats_left": 28,
    "window_seats": 11,
    "original_price": 520,
    "discounted_price": 470,
    "discount": 50,
    "policies": ["Free Cancellation", "Instant Refund"],
    "photos": [
      "https://media.istockphoto.com/id/1627383349/photo/bus-traveling-in-the-rainy-monsoon-season.webp?a=1&b=1&s=612x612&w=0&k=20&c=NXgtqJ4Z-5yX_iXnFGmOPuI7UwZhAdTzZhs_6JrEVqs=",
      "https://media.istockphoto.com/id/170586055/photo/parked-bus.webp?a=1&b=1&s=612x612&w=0&k=20&c=_DQXdmJdv5lfB-UJjxaZR-PQzdsCt66eWMBj0LCHeRM="
    ],
    "amenities": ["Charging Port", "Wi-Fi", "Blankets"],
    "pickups_drops": ["Chennai", "Vellore", "Bangalore"],
    "reviews_texts": ["Smooth ride", "Great driver"]
  },
  {
    'id':12,
    "name": "Jabbar Travels",
    "bus_type": "Ashok Leyland Non-A/C Sleeper (2+1)",
    "rating": 3.9,
    "review_count": 180,
    "departure_time": "21:00",
    "departure_date": "2021-09-12",
    "duration": "08hrs 45mins",
    "arrival_time": "05:45",
    "arrival_date": "2021-09-13",
    "seats_left": 35,
    "window_seats": 15,
    "original_price": 410,
    "discounted_price": 370,
    "discount": 40,
    "policies": ["Free Cancellation"],
    "photos": [
      "https://th.bing.com/th/id/OIP.Fp5pn8oYHd9I3C1G4eKC-wHaE8?w=259&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.hSDLzapgDDdEEdVRFhWLsQHaEo?w=289&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Charging Port", "Water Bottle"],
    "pickups_drops": ["Hyderabad", "Bangalore", "Anantapur"],
    "reviews_texts": ["Budget-friendly", "Smooth ride"]
  },
  {
    'id':13,
    "name": "VRL Logistics",
    "bus_type": "Volvo A/C Multi-Axle Semi-Sleeper (2+2)",
    "rating": 4.2,
    "review_count": 290,
    "departure_time": "22:15",
    "departure_date": "2021-09-16",
    "duration": "11hrs 00mins",
    "arrival_time": "09:15",
    "arrival_date": "2021-09-17",
    "seats_left": 25,
    "window_seats": 9,
    "original_price": 680,
    "discounted_price": 620,
    "discount": 60,
    "policies": ["Instant Refund"],
    "photos": [
      "https://th.bing.com/th/id/OIP.cn6kch83LT-NoZT5gWS95gHaEo?w=246&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.BLF2y0MW4CtCwr0T1dd6vgHaE7?w=273&h=182&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Wi-Fi", "Charging Port", "Blankets", "Snacks"],
    "pickups_drops": ["Hubli", "Bangalore", "Tumkur"],
    "reviews_texts": ["Good staff", "Punctual service"]
  },
  {
    'id':14,
    "name": "SRM Travels",
    "bus_type": "Scania Multi-Axle A/C Semi-Sleeper (2+2)",
    "rating": 4.7,
    "review_count": 315,
    "departure_time": "23:00",
    "departure_date": "2021-09-17",
    "duration": "08hrs 30mins",
    "arrival_time": "07:30",
    "arrival_date": "2021-09-17",
    "seats_left": 10,
    "window_seats": 3,
    "original_price": 750,
    "discounted_price": 700,
    "discount": 50,
    "policies": ["Free Cancellation"],
    "photos": [
      "https://th.bing.com/th/id/OIP.K5vww1erRbLZ0D71VpmPogHaEo?w=257&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.X6nI3jRJFY6VCp8yZF6zhQHaEK?w=249&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Charging Port", "Blankets", "Water Bottle", "Pillow"],
    "pickups_drops": ["Madurai", "Chennai", "Salem"],
    "reviews_texts": ["Luxurious bus", "On-time arrival"]
  },
  {
    'id':15,
    "name": "Kaleswari Travels",
    "bus_type": "Volvo A/C Seater/Sleeper (2+1)",
    "rating": 4.6,
    "review_count": 240,
    "departure_time": "22:40",
    "departure_date": "2021-09-13",
    "duration": "10hrs 15mins",
    "arrival_time": "08:55",
    "arrival_date": "2021-09-14",
    "seats_left": 8,
    "window_seats": 2,
    "original_price": 660,
    "discounted_price": 600,
    "discount": 60,
    "policies": ["Instant Refund"],
    "photos": [
      "https://th.bing.com/th/id/OIP.ZbDBXzOHzkIHBEVVzg8mWAHaLH?w=123&h=184&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.teTvZLLy_pwwZlOfkzFGAgEyDM?w=277&h=184&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Wi-Fi", "Charging Port", "Blankets"],
    "pickups_drops": ["Vijayawada", "Hyderabad", "Guntur"],
    "reviews_texts": ["Comfortable sleeper", "Good service"]
  },
  {
    'id':16,
    "name": "Morning Star Travels",
    "bus_type": "Ashok Leyland A/C Sleeper (2+1)",
    "rating": 4.1,
    "review_count": 210,
    "departure_time": "21:30",
    "departure_date": "2021-09-14",
    "duration": "09hrs 40mins",
    "arrival_time": "07:10",
    "arrival_date": "2021-09-15",
    "seats_left": 12,
    "window_seats": 4,
    "original_price": 540,
    "discounted_price": 490,
    "discount": 50,
    "policies": ["Free Cancellation"],
    "photos": [
      "https://th.bing.com/th/id/OIP.G5WhF1lu2zsuktq8sdV-pwHaEK?w=289&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.PqofFYu--ztRPePp9xrahQHaEJ?w=328&h=184&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Wi-Fi", "Charging Port", "Blankets", "Water Bottle"],
    "pickups_drops": ["Rajahmundry", "Hyderabad", "Chennai"],
    "reviews_texts": ["Affordable and clean", "Comfortable ride"]
  },
  {
    'id':17,
    "name": "Neeta Tours and Travels",
    "bus_type": "Volvo Multi-Axle Sleeper (2+1)",
    "rating": 4.3,
    "review_count": 245,
    "departure_time": "22:50",
    "departure_date": "2021-09-13",
    "duration": "10hrs 35mins",
    "arrival_time": "09:25",
    "arrival_date": "2021-09-14",
    "seats_left": 16,
    "window_seats": 6,
    "original_price": 590,
    "discounted_price": 530,
    "discount": 60,
    "policies": ["Free Cancellation"],
    "photos": [
      "https://th.bing.com/th/id/OIP.Fnyj1m7GIARA97bqVgs5yAHaEK?w=291&h=181&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.pGVd7RRrRf9FIq2OrTuyYgHaEK?w=321&h=181&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Charging Port", "Blankets", "Water Bottle", "Snacks"],
    "pickups_drops": ["Mumbai", "Pune", "Lonavala"],
    "reviews_texts": ["Good cleanliness", "Polite staff"]
  },
  {
    'id':18,
    "name": "Orange Tours and Travels",
    "bus_type": "Scania Multi-Axle Sleeper A/C (2+1)",
    "rating": 4.5,
    "review_count": 300,
    "departure_time": "21:10",
    "departure_date": "2021-09-12",
    "duration": "09hrs 10mins",
    "arrival_time": "06:20",
    "arrival_date": "2021-09-13",
    "seats_left": 5,
    "window_seats": 2,
    "original_price": 800,
    "discounted_price": 750,
    "discount": 50,
    "policies": ["Instant Refund"],
    "photos": [
      "https://th.bing.com/th/id/OIP.wTUSJcDG8k5kKyr8OsZn7gHaEK?w=254&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.rgUPfjt4rfFzohyzbg-kTwHaEK?w=254&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Charging Port", "Blankets", "Pillow", "Snacks"],
    "pickups_drops": ["Hyderabad", "Tirupati", "Vellore"],
    "reviews_texts": ["Luxury ride", "Best service"]
  },
  {
    'id':19,
    "name": "Parveen Travels",
    "bus_type": "Volvo A/C Seater Semi-Sleeper (2+2)",
    "rating": 4.4,
    "review_count": 220,
    "departure_time": "21:30",
    "departure_date": "2021-09-13",
    "duration": "09hrs 30mins",
    "arrival_time": "07:00",
    "arrival_date": "2021-09-14",
    "seats_left": 14,
    "window_seats": 5,
    "original_price": 500,
    "discounted_price": 450,
    "discount": 50,
    "policies": ["Free Cancellation", "Instant Refund"],
    "photos": [
      "https://th.bing.com/th/id/OIP.NNvGauTFalbTW6_sooeG0AHaEK?w=282&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.CqzEWkA3OMk6leNR3kHO5QAAAA?w=242&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Charging Port", "Blankets", "Water Bottle"],
    "pickups_drops": ["Trichy", "Chennai", "Vellore"],
    "reviews_texts": ["Comfortable seats", "Good for the price"]
  },
  {
    'id':20,
    "name": "SRS Travels",
    "bus_type": "Scania A/C Sleeper (2+1)",
    "rating": 4.9,
    "review_count": 310,
    "departure_time": "23:50",
    "departure_date": "2021-09-12",
    "duration": "08hrs 20mins",
    "arrival_time": "08:10",
    "arrival_date": "2021-09-13",
    "seats_left": 9,
    "window_seats": 3,
    "original_price": 780,
    "discounted_price": 720,
    "discount": 60,
    "policies": ["Free Cancellation"],
    "photos": [
      "https://th.bing.com/th/id/OIP.ndOfTaMAMEGx-C1YRkLqsgHaEK?w=333&h=187&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.ZcNMM2VDcfQoQfSp8M0CzgHaDe?w=301&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Wi-Fi", "Charging Port", "Blankets", "Water Bottle"],
    "pickups_drops": ["Mysore", "Bangalore", "Coimbatore"],
    "reviews_texts": ["Luxurious and comfortable", "Excellent service"]
  },
  {
    'id':21,
    "name": "VRL Travels",
    "bus_type": "Volvo Multi-Axle Semi-Sleeper (2+2)",
    "rating": 4.3,
    "review_count": 205,
    "departure_time": "22:30",
    "departure_date": "2021-09-15",
    "duration": "10hrs 45mins",
    "arrival_time": "09:15",
    "arrival_date": "2021-09-16",
    "seats_left": 12,
    "window_seats": 5,
    "original_price": 640,
    "discounted_price": 590,
    "discount": 50,
    "policies": ["Instant Refund"],
    "photos": [
      "https://th.bing.com/th/id/OIP.Qik8qHgOuZRU3WWLOzrWugHaE7?w=257&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.oK7rqBg3ey-o57bnIHCYIQHaFI?w=216&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Charging Port", "Water Bottle"],
    "pickups_drops": ["Pune", "Mumbai", "Navi Mumbai"],
    "reviews_texts": ["Timely departure", "Good staff"]
  },
  {
    'id':22,
    "name": "KPN Travels",
    "bus_type": "Ashok Leyland Non-A/C Sleeper (2+1)",
    "rating": 3.8,
    "review_count": 165,
    "departure_time": "20:15",
    "departure_date": "2021-09-14",
    "duration": "09hrs 50mins",
    "arrival_time": "06:05",
    "arrival_date": "2021-09-15",
    "seats_left": 22,
    "window_seats": 10,
    "original_price": 410,
    "discounted_price": 370,
    "discount": 40,
    "policies": ["Free Cancellation"],
    "photos": [
      "https://th.bing.com/th/id/OIP.7jvbxSSaAnvWbsM5IPj90AHaFj?w=229&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.pCcZQFbc8BufGQAPGHVx3gHaHa?w=193&h=194&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Charging Port", "Water Bottle"],
    "pickups_drops": ["Coimbatore", "Salem", "Chennai"],
    "reviews_texts": ["Affordable travel", "Decent service"]
  },
  {
    'id':23,
    "name": "Orange Tours and Travels",
    "bus_type": "Volvo A/C Sleeper (2+1)",
    "rating": 4.7,
    "review_count": 340,
    "departure_time": "21:00",
    "departure_date": "2021-09-15",
    "duration": "10hrs 00mins",
    "arrival_time": "07:00",
    "arrival_date": "2021-09-16",
    "seats_left": 7,
    "window_seats": 2,
    "original_price": 740,
    "discounted_price": 690,
    "discount": 50,
    "policies": ["Instant Refund"],
    "photos": [
      "https://th.bing.com/th/id/OIP.7KglIGlywPw18hlyE1NkZQHaFy?w=220&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.44Kt6zBfW1NQhKs_faItIwHaF-?w=233&h=187&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Wi-Fi", "Charging Port", "Blankets", "Water Bottle"],
    "pickups_drops": ["Hyderabad", "Bangalore", "Chennai"],
    "reviews_texts": ["Excellent bus", "Good amenities"]
  },
  {
    'id':24,
    "name": "Sugama Tourists",
    "bus_type": "Ashok Leyland A/C Sleeper (2+1)",
    "rating": 4.2,
    "review_count": 180,
    "departure_time": "22:45",
    "departure_date": "2021-09-14",
    "duration": "09hrs 15mins",
    "arrival_time": "08:00",
    "arrival_date": "2021-09-15",
    "seats_left": 10,
    "window_seats": 3,
    "original_price": 570,
    "discounted_price": 520,
    "discount": 50,
    "policies": ["Free Cancellation"],
    "photos": [
      "https://th.bing.com/th/id/OIP.vi0MvYOILwk-18wPkKXzLAHaEK?w=328&h=184&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP._AVMfDFKAp3NgHToGnR8iAHaHP?w=183&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Charging Port", "Blankets", "Water Bottle"],
    "pickups_drops": ["Mangalore", "Udupi", "Bangalore"],
    "reviews_texts": ["Comfortable journey", "Cleanliness maintained"]
  },
  {
    'id':25,
    "name": "Hebron Transports",
    "bus_type": "Mercedes Benz A/C Sleeper (2+1)",
    "rating": 4.6,
    "review_count": 250,
    "departure_time": "23:30",
    "departure_date": "2021-09-14",
    "duration": "08hrs 40mins",
    "arrival_time": "08:10",
    "arrival_date": "2021-09-15",
    "seats_left": 6,
    "window_seats": 2,
    "original_price": 850,
    "discounted_price": 800,
    "discount": 50,
    "policies": ["Instant Refund"],
    "photos": [
      "https://th.bing.com/th/id/OIP.i09H0pRv-8s7zq2L5SbcfgHaE4?w=311&h=175&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.EG1CrsTkjbceAsaFfd1g9QHaJp?w=227&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Wi-Fi", "Charging Port", "Blankets", "Water Bottle"],
    "pickups_drops": ["Bangalore", "Chennai", "Coimbatore"],
    "reviews_texts": ["Excellent service", "Very comfortable"]
  },
  {
    'id':26,
    "name": "SRS Travels",
    "bus_type": "Volvo A/C Sleeper (2+1)",
    "rating": 4.5,
    "review_count": 280,
    "departure_time": "22:00",
    "departure_date": "2021-09-16",
    "duration": "08hrs 50mins",
    "arrival_time": "06:50",
    "arrival_date": "2021-09-17",
    "seats_left": 11,
    "window_seats": 4,
    "original_price": 720,
    "discounted_price": 670,
    "discount": 50,
    "policies": ["Free Cancellation"],
    "photos": [
      "https://th.bing.com/th/id/OIP.4-i0QyoHJOL98cfM7ZaD6QHaG9?w=242&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.5Vm40IFpN3RBLHytX2bD4AHaEK?w=275&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Wi-Fi", "Charging Port", "Blankets"],
    "pickups_drops": ["Hyderabad", "Bangalore", "Chennai"],
    "reviews_texts": ["Very comfortable journey", "Great service"]
  },
  {
    'id':27,
    "name": "VRL Travels",
    "bus_type": "Volvo Multi-Axle A/C Sleeper (2+1)",
    "rating": 4.4,
    "review_count": 230,
    "departure_time": "20:30",
    "departure_date": "2021-09-16",
    "duration": "09hrs 00mins",
    "arrival_time": "05:30",
    "arrival_date": "2021-09-17",
    "seats_left": 8,
    "window_seats": 3,
    "original_price": 650,
    "discounted_price": 600,
    "discount": 50,
    "policies": ["Free Cancellation", "Instant Refund"],
    "photos": [
      "https://th.bing.com/th/id/OIP.zpmCl29u7BNIGZoANROdJgHaF5?w=333&h=188&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.njDmx4N0P1d0gQGflr8m7QHaHa?w=273&h=188&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Charging Port", "Water Bottle"],
    "pickups_drops": ["Pune", "Mumbai", "Surat"],
    "reviews_texts": ["Good comfort level", "On-time departure"]
  },
  {
    'id':28,
    "name": "Orange Tours and Travels",
    "bus_type": "Mercedes Benz A/C Sleeper (2+1)",
    "rating": 4.8,
    "review_count": 290,
    "departure_time": "23:00",
    "departure_date": "2021-09-15",
    "duration": "08hrs 50mins",
    "arrival_time": "07:50",
    "arrival_date": "2021-09-16",
    "seats_left": 9,
    "window_seats": 3,
    "original_price": 780,
    "discounted_price": 730,
    "discount": 50,
    "policies": ["Instant Refund"],
    "photos": [
      "https://th.bing.com/th/id/OIP.Ipq0SPXTnxFRNcr_2tvJ0QHaE8?w=284&h=178&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.Q3FEJ3ikYdAWmLMJZ_m8DgHaE8?w=221&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Wi-Fi", "Charging Port", "Blankets", "Water Bottle"],
    "pickups_drops": ["Bangalore", "Hyderabad", "Chennai"],
    "reviews_texts": ["Top-notch service", "Very comfortable"]
  },
  {
    'id':29,
    "name": "SRS Travels",
    "bus_type": "Volvo A/C Seater Semi-Sleeper (2+2)",
    "rating": 4.0,
    "review_count": 200,
    "departure_time": "21:30",
    "departure_date": "2021-09-16",
    "duration": "09hrs 00mins",
    "arrival_time": "06:30",
    "arrival_date": "2021-09-17",
    "seats_left": 15,
    "window_seats": 6,
    "original_price": 500,
    "discounted_price": 450,
    "discount": 50,
    "policies": ["Free Cancellation"],
    "photos": [
      "https://th.bing.com/th/id/OIP.0vRDpqV4W9e-7g4C9UNmLwHaFg?w=250&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.ZM9YO4EqO-xO9AqwbSlQWgHaGg?w=294&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Charging Port", "Water Bottle"],
    "pickups_drops": ["Mysore", "Bangalore", "Coimbatore"],
    "reviews_texts": ["Decent for the price", "Service could be improved"]
  },
  {
    'id':30,
    "name": "KPN Travels",
    "bus_type": "Ashok Leyland A/C Seater (2+2)",
    "rating": 3.9,
    "review_count": 190,
    "departure_time": "22:15",
    "departure_date": "2021-09-17",
    "duration": "08hrs 30mins",
    "arrival_time": "06:45",
    "arrival_date": "2021-09-18",
    "seats_left": 20,
    "window_seats": 8,
    "original_price": 450,
    "discounted_price": 400,
    "discount": 50,
    "policies": ["Free Cancellation"],
    "photos": [
      "https://th.bing.com/th/id/OIP.3NfGDoRBnICiTBZ0oNkKJwHaHa?w=235&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      "https://th.bing.com/th/id/OIP.lT_GkRdIs7KbFwQKHV1cbgHaEl?w=246&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
    ],
    "amenities": ["Charging Port", "Water Bottle"],
    "pickups_drops": ["Chennai", "Coimbatore", "Salem"],
    "reviews_texts": ["Affordable", "Basic amenities"]
  }
];
